# Voting Classifier

In [4]:
%run pipeline_utils.ipynb

(32560, 14)
(32560, 1)


In [ ]:
# from sklearn import model_selection
# from sklearn.linear_model import LogisticRegression
# from sklearn.naive_bayes import GaussianNB 
from sklearn.ensemble import RandomForestClassifier
# from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.svm import SVC
# from sklearn.metrics import roc_curve, auc

# clf1 = LogisticRegression(random_state=1)
# clf2 = RandomForestClassifier(random_state=1)
# clf3 = GaussianNB()
svmPipeline = Pipeline([
#     ("preprocess", preprocess),
    ("svm", SVC(probability=True))
])

mlpPipeline = Pipeline([
#     ('preprocess', preprocess),
    ('mlp', mlp.MLPClassifier())
])

rfPipeline = Pipeline([
#     ("preprocess", preprocess),
    ("rfc", RandomForestClassifier())
])

xgbPipeline = Pipeline([
#     ("preprocess", preprocess),
    # best params found after doing grid search on XG boost
    ("xgb", xgb.XGBClassifier(max_depth=5,subsample=0.6,colsample_bytree=1.0,gamma=2,min_child_weight=1))
])


estimators = [
    ('mlp', mlpPipeline),
    ('xgb', xgbPipeline),
    ('svm', svmPipeline)
]

# classifier = VotingClassifier(estimators,voting='soft',weights=[2,2,1])
# classifier.fit(Xtr,Ytr.ravel())

votingPipeline = Pipeline([
    ("preprocess", preprocess),
    ("VC", VotingClassifier(estimators,voting='soft',weights=[3,2,1]))
])

votingPipeline.fit(Xtr,Ytr.ravel())
# eclf = VotingClassifier(clfs=[clf1, clf2, clf3], voting='soft',weights=[1,1,1])
# labels = ['Logistic Regression', 'Random Forest', 'Naive Bayes']

# eclf.fit(Xtr,Ytr)
# pred = eclf.predict(Xva)
# print("Score: ",np.mean(pred==Yva))


In [14]:
auc(votingPipeline, Xtr, Ytr)

[0 0 0 ... 0 0 0]
F1 weighted 0.8949716705131096
AUC : 0.8307163489140892
Classification report : 
              precision    recall  f1-score   support

           0       0.91      0.96      0.94     22229
           1       0.85      0.70      0.77      7086

    accuracy                           0.90     29315
   macro avg       0.88      0.83      0.85     29315
weighted avg       0.90      0.90      0.89     29315

[[21388   841]
 [ 2131  4955]]
None


In [15]:
auc(votingPipeline, Xva, Yva)

[0 0 1 ... 0 1 1]
F1 weighted 0.8493881247503391
AUC : 0.7677833578365559
Classification report : 
              precision    recall  f1-score   support

           0       0.89      0.93      0.91      2491
           1       0.72      0.61      0.66       755

    accuracy                           0.85      3246
   macro avg       0.80      0.77      0.78      3246
weighted avg       0.85      0.85      0.85      3246

[[2314  177]
 [ 297  458]]
None


In [16]:
auc(votingPipeline,Xts,Yts)

[0 0 0 ... 0 0 1]
F1 weighted 0.8904040161483728
AUC : 0.8245813617165085
Classification report : 
              precision    recall  f1-score   support

           0       0.91      0.96      0.93     24719
           1       0.84      0.69      0.76      7841

    accuracy                           0.89     32560
   macro avg       0.87      0.82      0.85     32560
weighted avg       0.89      0.89      0.89     32560

[[23701  1018]
 [ 2428  5413]]
None


In [22]:
# import joblib
# joblib.dump(votingPipeline, 'voting_model.pkl', compress=1)

PicklingError: Can't pickle <function select_number at 0x7f241209e8c8>: it's not the same object as __main__.select_number

In [19]:
# votingPipeline = joblib.load('voting_model.pkl')

EOFError: 